import type { CSSProperties } from "react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  Braces,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  CircleDot,
  Code2,
  Copy,
  Database,
  Download,
  Eye,
  Files,
  Filter,
  FolderPlus,
  FoldVertical,
  GitBranch,
  Globe,
  History,
  Key,
  Keyboard,
  Layers,
  LayoutGrid,
  Minimize2,
  Moon,
  MoreHorizontal,
  PanelLeft,
  PanelRight,
  Pencil,
  Play,
  Plug,
  Plus,
  RefreshCw,
  Rows3,
  Save,
  Search,
  Send,
  Settings2,
  Sparkles,
  Square,
  Sun,
  Table2,
  Terminal,
  Trash2,
  UnfoldVertical,
  Users,
  WrapText,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-down": ArrowDown,
  "arrow-left": ChevronLeft,
  "arrow-right": ChevronRight,
  braces: Braces,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevrons-down": ChevronsDown,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "chevrons-up": ChevronsUp,
  cluster: Activity,
  code: Code2,
  copy: Copy,
  database: Database,
  docs: Files,
  download: Download,
  eye: Eye,
  filter: Filter,
  fold: FoldVertical,
  "folder-plus": FolderPlus,
  github: GitBranch,
  globe: Globe,
  groups: Users,
  history: History,
  key: Key,
  keyboard: Keyboard,
  "layout-grid": LayoutGrid,
  minify: Minimize2,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  plus: Plus,
  refresh: RefreshCw,
  rows: Rows3,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings2,
  sparkles: Sparkles,
  status: CircleDot,
  stop: Square,
  sun: Sun,
  table: Table2,
  terminal: Terminal,
  topics: Layers,
  trash: Trash2,
  unfold: UnfoldVertical,
  "wrap-text": WrapText,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

interface Props {
  name: IconName;
  size?: number;
  style?: CSSProperties;
  className?: string;
}

export function Icon({ name, size = 15, style, className }: Props) {
  const Component = ICONS[name];
  return <Component size={size} strokeWidth={1.8} style={{ flex: "none", ...style }} className={className} aria-hidden />;
}
